# Generated by Django 5.0.7 on 2024-10-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_tale_delete_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tale",
            name="number",
            field=models.CharField(max_length=4),
        ),
    ]
